# Use an official Python runtime as a base image
FROM tsutomu7/geopandas
# FROM jukermes/geopandas

# Set the working directory to /app 
# WORKDIR /app

# Copy the current directory contents into the container at /app
# ADD . /app

# Install any needed packages specified in requirements.txt
# RUN conda config --add channels conda-forge
# RUN conda config --add channels conda-forge
# RUN cat /root/.condarc
# RUN apt-get install build-essential -y
# RUN apt-get install python3.5 -y
# RUN apt-get install python3.5-pip -y
# RUN conda install geos
# RUN conda install -c conda-forge osmnx=0.5.1 -y
# RUN conda install -c conda-forge --yes --file requirements.txt
# RUN pip install -r requirements.txt
# RUN apt-get install nano

# Make port 80 available to the world outside this container
EXPOSE 3333

# Define environment variable 
# ENV NAME World

# Run app.py when the container launches 
# CMD ["python", "app.py"]

RUN echo "do this: 'sudo docker run --privileged=true -it -p 8888:8888 -v /vagrant/input/:/home/scientist/input -v /vagrant/output/:/home/scientist/output --name pythyme jcarvin/pythyme'"
